config/routes.rb
Rails.application.routes.draw do
 root 'pages#home'
 get 'about',to:'pages#about'
 resources:articles
 get 'signup',to:'users#new'
 resources:users, except:[:new]
 get 'login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'
 resources:categories, except:[:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title,presence:true,length:{minimum:6,maximum:100}
    validates :description,presence:true,length:{minimum:10,maximum:300}
end

app/models/article_category.rb
class ArticleCategory<ApplicationRecord
    belongs_to :category
    belongs_to :article
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name,presence:true,length: {minimum:3, maximum:25}
    validates_uniqueness_of :name
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord 
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy
    validates:username,presence:true,
                        uniqueness:{case_sensitive:false},
                        length:{minimum:3,maximum:25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates:email,presence:true,
                        uniqueness:{case_sensitive:false},
                        length:{maximum:105},
                        format: { with:VALID_EMAIL_REGEX}
                        
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    def logged_in?
        !!current_user
    end
    def login_requried
        if !logged_in?
            flash[:alert]="You Must be Logged in to perform that action"
            redirect_to login_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only:[:show,:edit,:update,:destroy]
    before_action :login_requried, except:[:show,:index]
    before_action :require_same_user, only:[:edit,:update,:destroy]
    def show
      
    end
    def index
        @articles=Article.paginate(page: params[:page], per_page: 5)
    end
    def new
        @article=Article.new
    end
    def edit
      
      
    end
    def create
        @article=Article.new(set_params)
        @article.user = current_user
       # render plain:@article.inspect
       if @article.save
        flash[:notice]="Data Created."
       redirect_to @article
       else 
       
        # render :new, status: :unprocessable_entity
        render 'new'

       end
    end
    def update 
        
       if @article.update(set_params)
        flash[:notice]="Artcle is updated"
        redirect_to @article
       else
        render 'new'
       end

    end
    def destroy
        
        @article.destroy
        redirect_to articles_path
    end
    private
    def set_article
        @article=Article.find(params[:id])
    end
    def set_params
        params.require(:article).permit(:title,:description, category_ids: [])
    end
    def require_same_user 
        if current_user!=@article.user && !current_user.admin?
            flash[:alert]="You can only edit or Detele Your Articles"
            redirect_to @article
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]

    def new
        @category=Category.new

    end
    def index
        @categories=Category.paginate(page: params[:page], per_page: 5)

    end
    def create 
        @category=Category.new(category_params)
        if @category.save
            flash[:notice]="Category was Successfully created"
            redirect_to @category
        else
            render 'new'
        end

    end
   
    def show 
        @category=Category.find(params[:id])
        @articles=@category.articles.paginate(page: params[:page], per_page: 5)
    end

    def edit
        @category=Category.find(params[:id])
        
    end

    def update
        @category=Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice]="Category name has Upated Successfully"
            redirect_to @category
        else
            render 'edit'
        end
    end

    private
    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admins can perform that action"
            redirect_to categories_path 
        end               
    end   
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end
    def about        
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
       user=User.find_by(email:params[:session][:email].downcase)
       puts "User found: #{user.inspect}"
       if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:notice]= "Logged in successfully."
        redirect_to user_path(user)
      else
      
        # If authentication fails, show an error message and re-render the login form
        flash.now[:alert] = "Invalid email/password combination."
        render "new"
      end 
    end

    def destroy
        session[:user_id] = nil
        flash[:notice]="Logged Out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user,only: [:show,:edit,:update,:destroy]
    before_action :login_requried,only: [:edit, :update]
    before_action :require_same_user,only: [:edit, :update,:destroy]
    def show
        
        @articles=@user.articles.paginate(page: params[:page], per_page: 5)
    end
    def index
        @users=User.paginate(page: params[:page], per_page: 5)
    end
    def new
        @user=User.new
    end
    def edit
        
    end
    def update
        
        if @user.update(user_params)
            
            flash[:notice]="Your Account is Updated Successfully"
            redirect_to @user
        else
            render 'edit'
        end
    end
    def create
        @user=User.new(user_params)
        if @user.save
            session[:user_id]=@user.id
            flash[:notice]="Welcome to TM Blog #{@user.username},You Successfully Signed Up"
            redirect_to articles_path
        else
            render 'new'
        end
    end
    def destroy
        @user.destroy
        session[:user_id]=nil if @user==current_user
        flash[:notice]="Account and all associated artiles are successfully deleted"
        redirect_to articles_path
    end
    private
    def user_params
        params.require(:user).permit(:username,:email,:password)
    end
    def set_user
        @user=User.find(params[:id])
    end
    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:alert]="You can Only edit and delete Your Account"
            redirect_to @user
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user,options={size:120})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size=options[:size]
        gravatar_url= "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url,alt:user.username,class:"rounded shadow-sm")
    end

   
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
 <div class="container">
    <% @articles.each do |article| %>
    <div class="row">
    <div class=" d-flex justify-content-center">
    <div class="card text-center col-8 mb-2 shadow-sm  border-0">
    <div class="card-header font-italic">
    <% if article.user%>

       <em> by <%= link_to article.user.username,user_path(article.user)  %></em>
       <%end%>
        <% if article.categories.any? %>
    <div class="mt-2 "><%= render article.categories %></div>
    <% else %>
    <div class="mt-2 text-secondary">No Categories have Add</div>
    <% end %>
    </div>
    <div class="card-body">
        <h5 class="card-title "><%= link_to article.title,article_path(article.id),class:"text-black text-decoration-none" %></h5>
        <p class="card-text"><%= truncate(article.description,length:100) %></p>
    <a><%= link_to 'View',article_path(article.id),class:"btn btn-success"%></a>
    <% if logged_in? && (article.user == current_user || current_user.admin?) %>
       <a><%= link_to 'Edit',edit_article_path(article.id),class:"btn btn-warning "%></a>
       <a><%= link_to'Delete',article_path(article.id), method: :delete,  data: {confirm: 'Are you sure?'},class:"btn btn-danger" %></a>
    <% end %>
    </div>
    <div class="card-footer text-muted">
        <small>Created <%= time_ago_in_words(article.created_at)%> Ago,</small>
<small>Updated <%= time_ago_in_words(article.updated_at)%> Ago</small>
    </div>
    </div>
    </div>
    </div>
    <%end%>
    </div>


<p><%=link_to 'Create',new_article_path%></p>

app/views/articles/_form.html.erb
<%= render 'shared/errors',obj:@article%>
<div class=" border p-5 bg-info bg-gradient text-white">
    <%= form_with(model: @article, local: true) do |f| %>
        <div class="f">
            <div class="form-group row">
                <%= f.label :title,class:"col-2 col-form-label"%>
                <%= f.text_field :title,class:"col-10 form-control",placeholder:"Enter Title"%>
            </div>
            <div class="form-group row"><%= f.label :description,class:"col-2 col-form-label"%>
                <%= f.text_area :description,class:"col-10 form-control",rows:10,placeholder:"Enter description"%>
            </div>
             <div class="form-group row"><%= f.label :Category,class:"col-2 col-form-label"%>
              <%= f.collection_select(:category_ids, Category.all, :id, :name,
               { prompt:"Make your selection from the list below (can be empty)"},{ multiple: true,size:3,class: "custom-select rounded"})%>
        
            </div>
            <div class="text-center"><%= f.submit class:"btn btn-success mt-2 "%></div>

        </div>
    <%end%>
</div>

app/views/articles/edit.html.erb
<div class="text-center"><h1>Edit Data</h1></div>

<div class="container"><%= render 'form'%></div>

app/views/articles/index.html.erb
<h1 class="text-center">Article Lish</h1>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
   <%=render 'article'%>
   <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

app/views/articles/new.html.erb
<div class="text-center"><h1>Create new Data</h1></div>

<div class="container"><%= render 'form'%></div>

app/views/articles/show.html.erb
<h1 class="text-center">Showing Details</h1>


<div class="container">
<div class="card">
  <div class="card-header text-center d-flex flex-column">
    by <%= @article.user.username if @article.user%><br>
    <%= link_to gravatar_for(@article.user),user_path(@article.user) %>
    <% if @article.categories.any? %>
    <div class="mt-2 "><%= render @article.categories %></div>
    <% end %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @article.title %></h5>
    <p class="card-text"><%= simple_format(@article.description) %></p>
    <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
      <a><%= link_to 'Edit',edit_article_path(@article),class:"btn btn-warning "%></a>
      <a><%= link_to'Delete',article_path(), method: :delete,  data: {confirm: 'Are you sure?'},class:"btn btn-danger" %></a>
    <%end%>
  </div>
</div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class:"badge rounded-pill text-bg-info mx-2 text-decoration-none" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors',obj:@category%>
<div class=" border p-5 bg-info bg-gradient text-white">
    <%= form_with(model: @category, local: true) do |f| %>
        <div class="f">
            <div class="form-group row">
                <%= f.label :name,"Category Name",class:"col-2 col-form-label"%>
                <%= f.text_field :name,class:"col-10 form-control",placeholder:"Enter User Name"%>
            </div>
           
            <div class="text-center"><%= f.submit  class:"btn btn-success mt-2 "%></div>

        </div>
    <%end%>
    
</div>

app/views/categories/edit.html.erb
<div class="text-center"><h1>Edit category</h1></div>
<div class="container">

<%= render "form" %>

<div class="d-flex justify-content-center m-5">
<%= link_to "[Cancel and return to category listing]",category_path(@category),class:'text-info' %>
</div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center">Category Lish</h1>
<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
  </div>
 <div class="container">
    <% @categories.each do |category| %>
    <div class="row">
    <div class=" d-flex justify-content-center">
    <div class="card text-center col-4 mb-2 shadow-sm  border-0">
   
    <div class="card-body ">
        <h5 class="card-title "><%= link_to category.name,category_path(category.id),class:" text-decoration-none text-success" %></h5>
        <p class="card-text"><%= pluralize(category.articles.count,"article") %></p>
    </div>
    <div class="card-footer text-muted">
        <small>Created <%= time_ago_in_words(category.created_at)%> Ago,</small>
<small>Updated <%= time_ago_in_words(category.updated_at)%> Ago</small>
    </div>
    </div>
    </div>
    </div>
    <%end%>
    </div>
    <div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
  </div>






  

app/views/categories/new.html.erb
<div class="text-center"><h1>Create a New category</h1></div>
<div class="container">

<%= render "form" %>

<div class="d-flex justify-content-center m-5">
<%= link_to "[Cancel and return to category listing]",categories_path,class:'text-info' %>
</div>

</div>

app/views/categories/show.html.erb
<div class="text-center "><h1>Category:<%=@category.name%></h1>

<h2>Articles List</h2>
<% if logged_in? && current_user.admin %>
<%= link_to "Edit Category profile", edit_category_path(@category), class:"btn btn-outline-info m-2"%>
<%end%>
</div>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
<%= render 'articles/article'%>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

app/views/layouts/_messages.html.erb
<div class="container"><%flash.each do |name,msg|%>
<% if name=notice%>
<div class="alert alert-success alert-dismissible fade show m-2" role="alert">
   <%=msg%>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<%elsif name=alert%>
<div class="alert alert-danger alert-dismissible fade show m-2" role="alert">
   <%=msg%>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<%end%>
 
  <%end%>
  </div>

app/views/layouts/_navigation.html.erb
 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>


<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
 <nav class="navbar navbar-dark bg-dark text-light d-flex justify-content-between">
  <!-- Navbar content -->


 <ul class="nav justify-content-center">
  <li class="nav-item">
    <%# <a class="nav-link active text-light" aria-current="page" href="#">hello</a> %>
    <%= link_to 'HOME',root_path,class:'nav-link active text-light'%>
  </li>

  <li class="nav-item">
    <%= link_to 'Bloggers',users_path,class:'nav-link active text-light'%>
  </li>


  <div class="dropdown nav-item bg-dark text-white">
  <button class="btn dropdown-toggle bg-dark text-white" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Article
  </button>
  <div class="dropdown-menu bg-dark text-white" aria-labelledby="dropdownMenuButton">
    <li class="nav-item">
    <%# <a class="nav-link text-light" href="#">Link</a> %>
     <%= link_to 'Articles',articles_path,class:'dropdown-item bg-dark text-white'%>
  </li>
    <%if logged_in? %>
  <li class="nav-item">
    <%= link_to 'Create Aricles', new_article_path,class:'dropdown-item bg-dark text-white'%>
  </li>
  <%end%>
    <a class="dropdown-item bg-dark text-white" href="#">Something else here</a>
  </div>
</div>
  <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
          <% end %>  
          <%= link_to "View categories", categories_path, class: "dropdown-item" %>
        </div>
      </li>



</ul>
<ul class="nav justify-content-center">
 
  <% if logged_in? %>
<div class="dropdown nav-item bg-dark text-white">
  <button class="btn dropdown-toggle bg-dark text-white" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
   <%="(Admin)" if current_user.admin?%> Profile[ <%= current_user.username%>]
  </button>
  <div class="dropdown-menu bg-dark text-white" aria-labelledby="dropdownMenuButton">
    <li class="nav-item">
    <%# <a class="nav-link text-light" href="#">Link</a> %>
     <%= link_to 'View Your Profile',user_path(current_user),class:'dropdown-item bg-dark text-white'%>
  </li>
    <li class="nav-item">
    <%= link_to 'Edit Your Profile',edit_user_path(current_user),class:'dropdown-item bg-dark text-white'%>
  </li>
    <%= link_to 'Delete Your Profile',user_path(current_user),class:'dropdown-item bg-dark text-danger',method: :delete,data:{confirm:"Are you Sure?"}%>
  </div>
</div>


   
   <li class="nav-item">
    <%= link_to 'Logout',logout_path,class:'nav-link active text-light', method: :delete %>
  </li>

  <%else%>
 <li class="nav-item">
    <%= link_to 'Log in',login_path,class:'nav-link active text-light'%>
  </li>
  <li class="nav-item">
    <%= link_to 'Sign Up',signup_path,class:'nav-link active text-light'%>
  </li>
  <%end%>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 
<%= render 'layouts/navigation'%>
  <%=render 'layouts/messages'%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
About
<p><%=link_to 'Go to index',articles_path%></p>
<p><%=link_to 'Home',root_path%></p>

app/views/pages/home.html.erb
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%# <img src="C:/Users/AJISH/OneDrive/Desktop/RubyonRails/blog/blog/app/assets/images/poster1.jpg" class="d-block w-100" alt="..."> %>
      <img class="d-block w-100" <%= image_tag("C:/Users/AJISH/OneDrive/Desktop/RubyonRails/blog/blog/app/assets/images/poster1.jpg")%> >
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item">
       <img class="d-block w-100" <%= image_tag("C:/Users/AJISH/OneDrive/Desktop/RubyonRails/blog/blog/app/assets/images/poster2.jpg")%> >
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" <%= image_tag("C:/Users/AJISH/OneDrive/Desktop/RubyonRails/blog/blog/app/assets/images/poster3.jpg")%> >
       <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<div class="d-flex justify-content-center">
<%# <button type="button" >Sign in</button> %>
<%= link_to 'Sign Up',signup_path, class:"btn btn-success btn-lg m-4 "%>
</div>
<p><%=link_to 'Go to index',articles_path%></p>
<p><%=link_to 'About',about_path%></p><div class="card" style="width: 18rem;">
 

app/views/shared/_errors.html.erb
<%if obj.errors.any?%>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h4 class="alert-heading">Please follow below errors in <%= obj.class.name.downcase%> form</h4>
  <ul>
<% obj.errors.full_messages.each do |msg|%>
<li><%=msg%></li>
<%end%>
</ul>
<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<%end%>
  

app/views/users/_form.html.erb
<%= render 'shared/errors',obj:@user%>
<div class=" border p-5 bg-info bg-gradient text-white">
    <%= form_with(model: @user, local: true) do |f| %>
        <div class="f">
            <div class="form-group row">
                <%= f.label :UserName,class:"col-2 col-form-label"%>
                <%= f.text_field :username,class:"col-10 form-control",placeholder:"Enter User Name"%>
            </div>
            <div class="form-group row">
                <%= f.label :Email,class:"col-2 col-form-label"%>
                <%= f.text_field :email,class:"col-10 form-control",placeholder:"Enter Email"%>
            </div>
            <div class="form-group row">
                <%= f.label :Password,class:"col-2 col-form-label"%>
                <%= f.password_field :password,class:"col-10 form-control",placeholder:"Enter password"%>
            </div>
            <div class="text-center"><%= f.submit(@user.new_record? ? "Sign Up": "Update Account", class:"btn btn-success mt-2 ")%></div>

        </div>
    <%end%>
</div>

app/views/users/edit.html.erb
<div class="text-center"><h1>Edit your Profile</h1></div>
<div class="container"><%= render 'form'%></div>

app/views/users/index.html.erb
<div class="text-center"><h1>Bloggers</h1></div> 
<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
  </div>
<div class="container">
    <% @users.each do |user| %>
    <div class="row">
    <div class=" d-flex justify-content-center">
    <div class="card text-center col-8 mb-2 shadow-sm  border-0">
    <div class="card-header font-italic">
       <em> by <%= link_to user.username,user %></em>
    </div>
    <div class="card-body">
        <h5 class="card-title "><%= link_to gravatar_for(user, size:120),user %></h5>
        <p class="card-text"><%= pluralize(user.articles.count,"article") %></p>
    <a><%= link_to 'View',user_path(user.id),class:"btn btn-success"%></a>
    <% if logged_in? %>
    <% if user==current_user%>
      <a><%= link_to 'Edit',edit_user_path(user.id),class:"btn btn-warning "%></a>
    <%end%>
    <%if current_user.admin? %>
      <a><%= link_to 'Delete User',user_path(user),class:"btn btn-danger ",method: :delete,data:{confirm:"Are you sure to delete this user"} %></a>
    <%end%>
    <%end%>
    </div>
    <div class="card-footer text-muted">
        <small>Joined <%= time_ago_in_words(user.created_at)%> Ago</small>
    </div>
    </div>
    </div>
    </div>
    <%end%>
    </div>
    <div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
  </div>

app/views/users/new.html.erb
<div class="text-center"><h1>SignUp Page</h1></div>
<div class="container"><%= render 'form'%></div>

app/views/users/show.html.erb
<div class="text-center"><h1><%=@user.username%>'s Profile</h1>

<%= gravatar_for @user, size:200%>
<h2>Articles List</h2>
<% if logged_in? && @user==current_user%>
<%= link_to "Edit user profile", edit_user_path(@user), class:"btn btn-outline-info m-2"%>
<%end%>
</div>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
<%= render 'articles/article'%>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>